### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by JonathonDunford** [SynDEX-Temporary-Name/SmartContract#13]
<a href="https://github.com/JonathonDunford"><img src="https://avatars1.githubusercontent.com/u/5281151?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [JonathonDunford](https://github.com/JonathonDunford)**
_Monday Mar 12, 2018 at 20:32 GMT_
_Originally opened as https://github.com/forkdelta/smart_contract/issues/22_

----

- [ ] Finish smart contract
- [ ] Detailed post with information on new smart contract, timeline, and instructions
- [ ] Community audit
- [ ] Several announcements about contract
- [ ] Official audit
- [ ] Reach out to DappRadar
- [ ] Reach out to DeltaBalances
- [ ] Launch

I was thinking of a tentative date of 04/05 for the launch.

At least 1 week before that for official audits.
At least 1 week before that for community audits.

Ideally, everything should be "done" by the 21st.

**Comment by JonathonDunford** [comment]
<a href="https://github.com/betterdelta"><img src="https://avatars2.githubusercontent.com/u/35501465?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [betterdelta](https://github.com/betterdelta)**
_Tuesday Mar 13, 2018 at 08:52 GMT_

----

"Finish smart contract" needs a better defintion, but maybe not in this issue.

How much time do we have until we actually want to deploy our contract?
Minus the time for community and external audit and we know how much time we have. 
Then we can decide what we want to implement.

**Comment by JonathonDunford** [comment]
<a href="https://github.com/JonathonDunford"><img src="https://avatars1.githubusercontent.com/u/5281151?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [JonathonDunford](https://github.com/JonathonDunford)**
_Wednesday Mar 14, 2018 at 15:00 GMT_

----

I was thinking of a tentative date of 04/05 for the launch.

At least 1 week before that for official audits.
At least 1 week before that for community audits.

Ideally, everything should be "done" by the 21st.

**Comment by JonathonDunford** [comment]
<a href="https://github.com/JonathonDunford"><img src="https://avatars1.githubusercontent.com/u/5281151?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [JonathonDunford](https://github.com/JonathonDunford)**
_Wednesday Mar 14, 2018 at 15:01 GMT_

----

We should have at least the versioning and truffle tests set up by then.
